### ISSUE TITLE
IBM Catalog

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-sandbox#3]
This project needs to be part of the IBM Catalog.

**Comment by alanngai** [comment]
pending IBM to move forward on this

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
