### ISSUE TITLE
Update references to the Lightbend helm-charts repo

### ISSUE THREAD

**Issue by marcoderama** [lightbend/reactive-sandbox#6]
The default location for the Lightbend helm-charts repo has moved to https://repo.lightbend.com/helm-charts and the old location (https://lightbend.github.io/helm-charts) is deprecated (and may go away at some point). sb-reactive-app should use the new location.

**Comment by marcoderama** [comment]
Suggested fix in PR https://github.com/lightbend/reactive-sandbox/pull/5

**Comment by dwijnand** [comment]
Fixed in #5.
